/*
 * This file is generated by jOOQ.
 */
package com.bensen.rating.db.jooq.tables.records;


import com.bensen.rating.db.jooq.tables.Player;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends UpdatableRecordImpl<PlayerRecord> implements Record5<UUID, String, Integer, Integer, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.player.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.player.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.player.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.player.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.player.solo_rating</code>.
     */
    public void setSoloRating(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.player.solo_rating</code>.
     */
    public Integer getSoloRating() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.player.team_rating</code>.
     */
    public void setTeamRating(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.player.team_rating</code>.
     */
    public Integer getTeamRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.player.modified_date</code>.
     */
    public void setModifiedDate(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.player.modified_date</code>.
     */
    public OffsetDateTime getModifiedDate() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, Integer, Integer, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, Integer, Integer, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Player.PLAYER.ID;
    }

    @Override
    public Field<String> field2() {
        return Player.PLAYER.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Player.PLAYER.SOLO_RATING;
    }

    @Override
    public Field<Integer> field4() {
        return Player.PLAYER.TEAM_RATING;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Player.PLAYER.MODIFIED_DATE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getSoloRating();
    }

    @Override
    public Integer component4() {
        return getTeamRating();
    }

    @Override
    public OffsetDateTime component5() {
        return getModifiedDate();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getSoloRating();
    }

    @Override
    public Integer value4() {
        return getTeamRating();
    }

    @Override
    public OffsetDateTime value5() {
        return getModifiedDate();
    }

    @Override
    public PlayerRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public PlayerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlayerRecord value3(Integer value) {
        setSoloRating(value);
        return this;
    }

    @Override
    public PlayerRecord value4(Integer value) {
        setTeamRating(value);
        return this;
    }

    @Override
    public PlayerRecord value5(OffsetDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public PlayerRecord values(UUID value1, String value2, Integer value3, Integer value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRecord
     */
    public PlayerRecord() {
        super(Player.PLAYER);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(UUID id, String name, Integer soloRating, Integer teamRating, OffsetDateTime modifiedDate) {
        super(Player.PLAYER);

        setId(id);
        setName(name);
        setSoloRating(soloRating);
        setTeamRating(teamRating);
        setModifiedDate(modifiedDate);
    }
}
