/*
 * This file is generated by jOOQ.
 */
package com.bensen.rating.db.jooq;


import com.bensen.rating.db.jooq.tables.FlywaySchemaHistory;
import com.bensen.rating.db.jooq.tables.Player;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;
}
